# Generated by Django 5.1.3 on 2024-11-06 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ruc_receptor', models.CharField(max_length=20)),
                ('fecha_factura', models.DateField()),
                ('iAmb', models.CharField(max_length=10)),
                ('iTpEmis', models.CharField(max_length=10)),
                ('iDoc', models.CharField(max_length=10)),
                ('dNroDF', models.CharField(max_length=20)),
                ('dPtoFacDF', models.CharField(max_length=10)),
                ('dSeg', models.CharField(max_length=20)),
                ('dFechaEm', models.DateField()),
                ('dFechaSalida', models.DateField(blank=True, null=True)),
                ('iNatOp', models.CharField(max_length=10)),
                ('iTipoOp', models.CharField(max_length=10)),
                ('iDest', models.CharField(max_length=10)),
                ('iFormCAFE', models.CharField(max_length=10)),
                ('iEntCAFE', models.CharField(max_length=10)),
                ('dEnvFE', models.CharField(max_length=20)),
                ('iProGen', models.CharField(max_length=10)),
                ('iTipoTranVenta', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dTipoRuc', models.CharField(max_length=10)),
                ('dRuc', models.CharField(max_length=20)),
                ('dDV', models.CharField(max_length=5)),
                ('dNombEm', models.CharField(max_length=100)),
                ('dSucEm', models.CharField(max_length=10)),
                ('dCoordEm', models.CharField(max_length=50)),
                ('dDirecEm', models.CharField(max_length=255)),
                ('dCodUbi', models.CharField(max_length=10)),
                ('dCorreg', models.CharField(max_length=50)),
                ('dDistr', models.CharField(max_length=50)),
                ('dProv', models.CharField(max_length=50)),
                ('dTfnEm', models.CharField(max_length=15)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='invoices.factura')),
            ],
        ),
        migrations.CreateModel(
            name='FirmaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CanonicalizationMethod', models.CharField(max_length=100)),
                ('SignatureMethod', models.CharField(max_length=100)),
                ('Transforms', models.CharField(max_length=100)),
                ('DigestMethod', models.CharField(max_length=100)),
                ('DigestValue', models.CharField(max_length=255)),
                ('SignatureValue', models.TextField()),
                ('X509SubjectName', models.TextField()),
                ('X509Certificate', models.TextField()),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_digital', to='invoices.factura')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dSecItem', models.IntegerField()),
                ('dDescProd', models.CharField(max_length=255)),
                ('dCodProd', models.CharField(max_length=50)),
                ('dCantCodInt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dCodCPBScmp', models.CharField(max_length=50)),
                ('dPrUnit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dPrUnitDesc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dPrItem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dPrAcarItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dPrSegItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dValTotItem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dTasaITBMS', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dValITBMS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.factura')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dNroPed', models.CharField(max_length=20)),
                ('dCodSisEm', models.CharField(max_length=20)),
                ('dInfEmPedGl', models.TextField(blank=True, null=True)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_comercial', to='invoices.factura')),
            ],
        ),
        migrations.CreateModel(
            name='QRFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dQRCode', models.ImageField(upload_to='qr_codes/')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_factura', to='invoices.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iTipoRec', models.CharField(max_length=10)),
                ('dTipoRuc', models.CharField(max_length=10)),
                ('dRuc', models.CharField(max_length=20)),
                ('dNombRec', models.CharField(max_length=100)),
                ('cPaisRec', models.CharField(max_length=3)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='invoices.factura')),
            ],
        ),
        migrations.CreateModel(
            name='TotalesFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dTotNeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dTotITBMS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dTotGravado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dTotDesc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dVTot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dTotRec', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iPzPag', models.CharField(max_length=20)),
                ('dNroItems', models.IntegerField()),
                ('dVTotItems', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iFormaPago', models.CharField(max_length=20)),
                ('dVlrCuota', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totales', to='invoices.factura')),
            ],
        ),
    ]
